// import React from "react";


const Mobile_common_product=[
    {
        id:1,
        imgsrc:"./Mobile_images/realme_C_51.webp",
        title:'realme C51 (Mint Green, 64 GB)',
        price:8999,
        old_price:10999,
        storage:'4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
        display:'17.12 cm (6.74 inch) HD Display',
        camera:'50MP + 0.08MP | 5MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
    },
    {
        id:2,
        imgsrc:"./Mobile_images/realme_11x.webp",
        title:'realme 11x 5G (Purple Dawn, 128 GB)',
        price:15999,
        old_price:18999,
        storage:'8 GB RAM | 128 GB ROM | Expandable Upto 2 TB',
        display:'17.07 cm (6.72 inch) Full HD+ Display',
        camera:'64MP + 2MP | 8MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
    },
    {
        id:3,
        imgsrc:'./Mobile_images/samsung_F13.webp',
        title:'SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)',
        price:9199,
        old_price:1499,
        storage:'4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
        display:'16.76 cm (6.6 inch) Full HD+ Display',
        camera:'50MP + 5MP + 2MP | 8MP Front Camera',
        bettry:'6000 mAh Lithium Ion Battery',
        warranty:'1 Year Warranty Provided By the Manufacturer from Date of Purchase',
    },
    {
        id:4,
        imgsrc:'./Mobile_images/samsung_M14.webp',
        title:'SAMSUNG Galaxy M14 5G (Smoky Teal, 128 GB)',
        price:14300,
        old_price:18999,
        storage:'6 GB RAM | 128 GB ROM',
        display:'16.76 cm (6.6 inch) Display',
        camera:'50MP Rear Camera',
        bettry:'6000 mAh Battery',
        warranty:'1 year manufacturer for handset and 6 month for accessories',
    },
    {
        id:5,
        imgsrc:'./Mobile_images/oneplush_cc.webp',
        title:'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)',
        price:17044,
        old_price:1999,
        storage:'6 GB RAM | 128 GB ROM',
        display:'16.74 cm (6.59 inch) Display',
        camera:'64MP Rear Camera | 16MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'12 Months',
    },
    {
        id:6,
        imgsrc:'./Mobile_images/iphone-13.webp',
        title:'APPLE iPhone 13 (Midnight, 128 GB)',
        price:52499,
        old_price:59990,
        storage:'128 GB ROM',
        display:'15.49 cm (6.1 inch) Super Retina XDR Display',
        camera:'12MP + 12MP | 12MP Front Camera',
        bettry:'A15 Bionic Chip Processor',
        warranty:'Brand Warranty for 1 Year',
    },
    {
        id:7,
        imgsrc:'./Mobile_images/vivo_T2x.webp',
        title:'vivo T2x 5G (Glimmer Black, 128 GB)',
        price:15999,
        old_price:20999,
        storage:'8 GB RAM | 128 GB ROM',
        display:'16.71 cm (6.58 inch) Full HD+ Display',
        camera:'50MP + 2MP | 8MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year of Device & 6 Months for Inbox Accessories',
    },
    {
        id:8,
        imgsrc:'./Mobile_images/Redmi_12.webp',
        title:'REDMI 12 (Moonstone Silver, 128 GB)',
        price:9999,
        old_price:14999,
        storage:'4 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
        display:'17.25 cm (6.79 inch) Full HD+ Display',
        camera:'50MP + 8MP + 2MP | 8MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories',
    },
    {
        id:9,
        imgsrc:'./Mobile_images/realme_11x.webp',
        title:'Classic Cumin Seeds by Flipkart Grocery',
        price:81,
        old_price:105,
        storage:'4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
        display:'17.12 cm (6.74 inch) HD Display',
        camera:'50MP + 0.08MP | 5MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
    },
    {
        id:10,
        imgsrc:'./Mobile_images/samsung_M14.webp',
        title:'Classic Turmeric Powder by Flipkart Grocery',
        price:63,
        old_price:120,
        storage:'4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
        display:'17.12 cm (6.74 inch) HD Display',
        camera:'50MP + 0.08MP | 5MP Front Camera',
        bettry:'5000 mAh Battery',
        warranty:'1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
    }
]







export default Mobile_common_product;